name: CI

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Sync-charging-map-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: node ./scripts/sync.mjs
      - name: Commit files
        run: |
          git add ./data
          git config --local user.email "liam@freighter.studio"
          git config --local user.name "Liam Martens"
          git commit -m "Updated charging spots"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}